# Arco Catalog Alert Rules
#
# These alerts are designed for Prometheus/Alertmanager and can be adapted
# for Cloud Monitoring or other alerting systems.
#
# Per M8 Task 8.3 requirements:
# - API error rate > 1% for 5 min
# - Compaction lag > 10 min
# - CAS retry rate > 10/min
# - Rate limit hits > 100/min per endpoint

groups:
  - name: arco.api
    rules:
      # API Error Rate Alert
      # Fires when error rate exceeds 1% for 5 minutes
      - alert: ArcoApiErrorRateHigh
        expr: |
          sum(rate(api_request_total{status_class="5xx"}[5m]))
          / sum(rate(api_request_total[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
          service: arco-api
        annotations:
          summary: "API 5xx error rate > 1%"
          description: |
            The Arco API 5xx error rate has exceeded 1% for 5 minutes.
            Current rate: {{ $value | printf "%.2f" }}%
          runbook_url: "https://docs.arco.dev/runbooks/api-errors"

      # API High Latency Alert
      - alert: ArcoApiLatencyHigh
        expr: |
          histogram_quantile(0.95, sum(rate(api_request_duration_seconds_bucket[5m])) by (le, endpoint))
          > 1.0
        for: 5m
        labels:
          severity: warning
          service: arco-api
        annotations:
          summary: "API p95 latency > 1s for {{ $labels.endpoint }}"
          description: |
            The Arco API endpoint {{ $labels.endpoint }} has p95 latency exceeding 1 second.
            Current p95: {{ $value | printf "%.2f" }}s
          runbook_url: "https://docs.arco.dev/runbooks/slow-requests"

      # Rate Limit Hits Alert
      # Fires when any endpoint exceeds 100 rate limit hits per minute
      - alert: ArcoRateLimitHitsHigh
        expr: |
          sum by (endpoint) (increase(rate_limit_hits_total[1m])) > 100
        for: 1m
        labels:
          severity: warning
          service: arco-api
        annotations:
          summary: "Rate limit hits > 100/min for endpoint {{ $labels.endpoint }}"
          description: |
            Endpoint {{ $labels.endpoint }} is hitting rate limits frequently.
            Rate: {{ $value | printf "%.0f" }} hits/min
          runbook_url: "https://docs.arco.dev/runbooks/rate-limiting"

  - name: arco.compactor
    rules:
      # Compaction Lag Alert
      # Fires when compaction lag exceeds 10 minutes
      - alert: ArcoCompactionLagHigh
        expr: compaction_lag_seconds > 600
        for: 5m
        labels:
          severity: warning
          service: arco-compactor
        annotations:
          summary: "Compaction lag > 10 minutes for domain {{ $labels.domain }}"
          description: |
            Compaction for domain {{ $labels.domain }} has not completed recently.
            Current lag proxy: {{ $value | printf "%.0f" }} seconds
          runbook_url: "https://docs.arco.dev/runbooks/compactor-stuck"

      # Compactor Not Running Alert
      # Fires when no compaction cycles complete in 24 hours
      - alert: ArcoCompactorNotRunning
        expr: |
          sum(increase(compaction_cycles_total[24h])) == 0
        for: 1h
        labels:
          severity: critical
          service: arco-compactor
        annotations:
          summary: "Compactor has not run in 24 hours"
          description: |
            No compaction cycle has completed in the last 24 hours.
            This may indicate the compactor is down or stuck.
          runbook_url: "https://docs.arco.dev/runbooks/compactor-stuck"

      # CAS Retry Rate Alert
      # Fires when CAS retries exceed 10/min
      - alert: ArcoCasRetryRateHigh
        expr: |
          sum by (operation) (increase(cas_retry_total[1m])) > 10
        for: 5m
        labels:
          severity: warning
          service: arco-catalog
        annotations:
          summary: "CAS retry rate > 10/min for {{ $labels.operation }}"
          description: |
            High CAS retry rate indicates contention on catalog writes.
            Current rate: {{ $value | printf "%.1f" }} retries/min
          runbook_url: "https://docs.arco.dev/runbooks/cas-contention"

  - name: arco.gc
    rules:
      # GC Not Running Alert
      - alert: ArcoGCNotRunning
        expr: |
          sum(increase(arco_gc_run_duration_seconds_count[24h])) == 0
        for: 1h
        labels:
          severity: warning
          service: arco-gc
        annotations:
          summary: "GC has not run in 24 hours"
          description: |
            Garbage collection has not run in the last 24 hours.
            Storage costs may be increasing.
          runbook_url: "https://docs.arco.dev/runbooks/gc-failure"

      # GC Errors Alert
      - alert: ArcoGCErrors
        expr: increase(arco_gc_errors_total[1h]) > 0
        for: 5m
        labels:
          severity: warning
          service: arco-gc
        annotations:
          summary: "GC encountered errors"
          description: |
            Garbage collection encountered {{ $value | printf "%.0f" }} errors in the last hour.
            Phase: {{ $labels.phase }}
          runbook_url: "https://docs.arco.dev/runbooks/gc-failure"

  - name: arco.orchestration
    rules:
      - alert: ArcoOrchBacklogDepthHigh
        expr: max by (lane) (arco_orch_backlog_depth) > 200
        for: 5m
        labels:
          severity: warning
          service: arco-flow
        annotations:
          summary: "Orchestration backlog depth high (lane={{ $labels.lane }})"
          description: |
            The orchestration backlog depth exceeded 200 in lane {{ $labels.lane }}.
            Current depth: {{ $value | printf "%.0f" }}
          runbook_url: "https://docs.arco.dev/runbooks/scheduler-not-progressing"

      - alert: ArcoOrchCompactionLagHigh
        expr: max(arco_orch_compaction_lag_seconds) > 30
        for: 5m
        labels:
          severity: warning
          service: arco-flow
        annotations:
          summary: "Orchestration compaction lag high"
          description: |
            Compaction lag exceeded 30 seconds.
            Current lag: {{ $value | printf "%.2f" }}s
          runbook_url: "https://docs.arco.dev/runbooks/compactor-stuck"

      - alert: ArcoOrchRunKeyConflictsDetected
        expr: max(arco_orch_run_key_conflicts) > 0
        for: 10m
        labels:
          severity: warning
          service: arco-flow
        annotations:
          summary: "Run-key conflicts detected"
          description: |
            Durable run-key conflict rows are present.
            Current count: {{ $value | printf "%.0f" }}
          runbook_url: "https://docs.arco.dev/runbooks/scheduler-not-progressing"

      - alert: ArcoOrchControllerReconcileP95High
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(arco_orch_controller_reconcile_seconds_bucket[5m])) by (le, controller)
          ) > 2
        for: 10m
        labels:
          severity: warning
          service: arco-flow
        annotations:
          summary: "Controller reconcile p95 latency high (controller={{ $labels.controller }})"
          description: |
            Reconcile p95 latency exceeded 2s for controller {{ $labels.controller }}.
            Current p95: {{ $value | printf "%.3f" }}s
          runbook_url: "https://docs.arco.dev/runbooks/scheduler-not-progressing"

      - alert: ArcoOrchSloObservedAboveTarget
        expr: |
          max by (slo) (arco_orch_slo_observed_seconds)
          > on (slo)
          max by (slo) (arco_orch_slo_target_seconds)
        for: 5m
        labels:
          severity: warning
          service: arco-flow
        annotations:
          summary: "Observed orchestration SLO exceeded target (slo={{ $labels.slo }})"
          description: |
            Observed SLO value is above target for {{ $labels.slo }}.
            Current observed: {{ $value | printf "%.3f" }}s
          runbook_url: "https://docs.arco.dev/runbooks/scheduler-not-progressing"

      - alert: ArcoOrchSloBreachesIncreasing
        expr: sum by (slo) (increase(arco_orch_slo_breaches_total[5m])) > 0
        for: 1m
        labels:
          severity: critical
          service: arco-flow
        annotations:
          summary: "Orchestration SLO breaches are increasing (slo={{ $labels.slo }})"
          description: |
            Runtime SLO breach counter increased in the last 5 minutes for {{ $labels.slo }}.
            Increase: {{ $value | printf "%.0f" }}
          runbook_url: "https://docs.arco.dev/runbooks/scheduler-not-progressing"
