[package]
name = "arco-storage-s3"
description = "Amazon S3 adapter for Arco storage contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
arco-core = { path = "../arco-core", default-features = false }
arco-storage-object-store = { path = "../arco-storage-object-store" }
async-trait = { workspace = true }
bytes = { workspace = true }
object_store = { workspace = true, features = ["aws"] }

arco-catalog = { path = "../arco-catalog", default-features = false, optional = true }
serde_json = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
http = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
ulid = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
ulid = { workspace = true }

[features]
qualification = ["dep:arco-catalog", "dep:serde_json", "dep:serde", "dep:sha2", "dep:futures", "dep:http", "dep:chrono", "dep:tokio", "dep:ulid"]

[[bin]]
name = "arco-state-store-qualification"
path = "src/bin/qualification.rs"
required-features = ["qualification"]
