//! Sensor evaluation interfaces.

use std::collections::HashMap;
use std::fmt;

use chrono::{DateTime, Utc};

use crate::orchestration::events::RunRequest;

/// Pub/Sub message for push sensor evaluation.
#[derive(Debug, Clone)]
pub struct PubSubMessage {
    /// Unique message identifier (for idempotency).
    pub message_id: String,
    /// Message payload.
    pub data: Vec<u8>,
    /// Message attributes.
    pub attributes: HashMap<String, String>,
    /// When the message was published.
    pub publish_time: DateTime<Utc>,
}

/// Result of evaluating a poll sensor.
#[derive(Debug, Clone)]
pub struct PollSensorResult {
    /// Cursor after evaluation (None means "do not advance").
    pub cursor_after: Option<String>,
    /// Run requests generated by this evaluation.
    pub run_requests: Vec<RunRequest>,
}

/// Error returned by sensor evaluation logic.
#[derive(Debug, Clone)]
pub struct SensorEvaluationError {
    /// Error message describing the failure.
    pub message: String,
}

impl SensorEvaluationError {
    /// Creates a new evaluation error.
    #[must_use]
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for SensorEvaluationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for SensorEvaluationError {}

impl From<String> for SensorEvaluationError {
    fn from(message: String) -> Self {
        Self { message }
    }
}

impl From<&str> for SensorEvaluationError {
    fn from(message: &str) -> Self {
        Self {
            message: message.to_string(),
        }
    }
}

/// Interface for evaluating push and poll sensors.
pub trait SensorEvaluator: Send + Sync {
    /// Evaluate a push sensor given a Pub/Sub message.
    fn evaluate_push(
        &self,
        sensor_id: &str,
        message: &PubSubMessage,
    ) -> Result<Vec<RunRequest>, SensorEvaluationError>;

    /// Evaluate a poll sensor given the current cursor.
    fn evaluate_poll(
        &self,
        sensor_id: &str,
        cursor_before: Option<&str>,
    ) -> Result<PollSensorResult, SensorEvaluationError>;
}

/// No-op evaluator for tests and default wiring.
#[derive(Debug, Default)]
pub struct NoopSensorEvaluator;

impl SensorEvaluator for NoopSensorEvaluator {
    fn evaluate_push(
        &self,
        _sensor_id: &str,
        _message: &PubSubMessage,
    ) -> Result<Vec<RunRequest>, SensorEvaluationError> {
        Ok(Vec::new())
    }

    fn evaluate_poll(
        &self,
        _sensor_id: &str,
        cursor_before: Option<&str>,
    ) -> Result<PollSensorResult, SensorEvaluationError> {
        Ok(PollSensorResult {
            cursor_after: cursor_before.map(|cursor| format!("{cursor}_advanced")),
            run_requests: Vec::new(),
        })
    }
}
