name: Release SBOM

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Annotated signed release tag (for example: v1.2.3)"
        required: true
        type: string

permissions:
  contents: write
  attestations: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SBOM_RETENTION_DAYS: 90

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Resolve release tag context
        run: |
          RELEASE_TAG="${GITHUB_REF_NAME}"
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            RELEASE_TAG="${{ inputs.release_tag }}"
          fi

          if [ -z "${RELEASE_TAG}" ]; then
            echo "release tag is required for SBOM workflow" >&2
            exit 1
          fi

          echo "RELEASE_TAG=${RELEASE_TAG}" >> "${GITHUB_ENV}"
          echo "SBOM_SPDX_FILE=arco-${RELEASE_TAG}.spdx.json" >> "${GITHUB_ENV}"
          echo "SBOM_CYCLONEDX_FILE=arco-${RELEASE_TAG}.cyclonedx.json" >> "${GITHUB_ENV}"
          echo "SBOM_SHA256_FILE=arco-${RELEASE_TAG}.sbom.sha256" >> "${GITHUB_ENV}"
          echo "EVIDENCE_ARCHIVE=arco-${RELEASE_TAG}.release-evidence.tgz" >> "${GITHUB_ENV}"

      - name: Validate changelog + release notes completeness
        run: bash tools/check-release-tag-discipline.sh --tag "${RELEASE_TAG}"

      - name: Validate annotated signed release tag
        run: |
          git fetch --force --tags origin
          git cat-file -e "${RELEASE_TAG}^{tag}"
          git cat-file -p "${RELEASE_TAG}^{tag}" > "arco-${RELEASE_TAG}.tag-object.txt"

          if ! rg -q '^-----BEGIN (PGP|SSH) SIGNATURE-----$' "arco-${RELEASE_TAG}.tag-object.txt"; then
            echo "release tag must include a PGP or SSH signature block: ${RELEASE_TAG}" >&2
            exit 1
          fi

      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          toolchain: 1.85

      - name: Install cargo-sbom
        uses: taiki-e/install-action@887bc4e03483810873d617344dd5189cd82e7b8b # v2
        with:
          tool: cargo-sbom@0.10.0

      - name: Generate SBOM (SPDX JSON)
        run: cargo sbom --output-format spdx_json_2_3 > "${SBOM_SPDX_FILE}"

      - name: Generate SBOM (CycloneDX JSON)
        run: cargo sbom --output-format cyclone_dx_json_1_6 > "${SBOM_CYCLONEDX_FILE}"

      - name: Generate SBOM checksum manifest
        run: |
          sha256sum "${SBOM_SPDX_FILE}" "${SBOM_CYCLONEDX_FILE}" > "${SBOM_SHA256_FILE}"

      - name: Upload release SBOM artifact pack (retained)
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: release-sbom-${{ env.RELEASE_TAG }}
          retention-days: ${{ env.SBOM_RETENTION_DAYS }}
          if-no-files-found: error
          path: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}
            arco-${{ env.RELEASE_TAG }}.tag-object.txt

      - name: Publish build provenance attestation for SBOM artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}

      - name: Attach SBOM files to GitHub release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}

      - name: Build immutable release evidence pack
        run: |
          PACK_DIR="$(bash tools/collect_release_evidence.sh --tag "${RELEASE_TAG}" --output-root ".gate1-collector")"
          echo "PACK_DIR=${PACK_DIR}" >> "${GITHUB_ENV}"

      - name: Archive release evidence pack
        run: |
          tar -C "$(dirname "${PACK_DIR}")" -czf "${EVIDENCE_ARCHIVE}" "$(basename "${PACK_DIR}")"

      - name: Upload release evidence pack artifact (retained)
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: release-evidence-${{ env.RELEASE_TAG }}
          retention-days: ${{ env.SBOM_RETENTION_DAYS }}
          if-no-files-found: error
          path: ${{ env.EVIDENCE_ARCHIVE }}
