name: Release SBOM

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Annotated signed release tag (for example: v1.2.3)"
        required: true
        type: string

permissions:
  contents: write
  attestations: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SBOM_RETENTION_DAYS: 90
  RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.release_tag || github.ref_name }}

jobs:
  sbom:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ env.RELEASE_TAG }}

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Resolve and validate release tag context
        run: |
          if [ -z "${RELEASE_TAG}" ]; then
            echo "release tag is required for SBOM workflow" >&2
            exit 1
          fi

          if [[ ! "${RELEASE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
            echo "release tag must match vMAJOR.MINOR.PATCH (optionally suffixed): ${RELEASE_TAG}" >&2
            exit 1
          fi

          git fetch --force --tags origin
          git cat-file -e "${RELEASE_TAG}^{tag}"

          TAG_COMMIT_SHA="$(git rev-list -n 1 "${RELEASE_TAG}^{commit}")"
          HEAD_SHA="$(git rev-parse HEAD)"
          if [ "${HEAD_SHA}" != "${TAG_COMMIT_SHA}" ]; then
            echo "checked out commit (${HEAD_SHA}) does not match tag commit (${TAG_COMMIT_SHA}) for ${RELEASE_TAG}" >&2
            exit 1
          fi

          echo "TAG_COMMIT_SHA=${TAG_COMMIT_SHA}" >> "${GITHUB_ENV}"
          echo "SBOM_SPDX_FILE=arco-${RELEASE_TAG}.spdx.json" >> "${GITHUB_ENV}"
          echo "SBOM_CYCLONEDX_FILE=arco-${RELEASE_TAG}.cyclonedx.json" >> "${GITHUB_ENV}"
          echo "SBOM_SHA256_FILE=arco-${RELEASE_TAG}.sbom.sha256" >> "${GITHUB_ENV}"
          echo "EVIDENCE_ARCHIVE=arco-${RELEASE_TAG}.release-evidence.tgz" >> "${GITHUB_ENV}"

      - name: Wait for release-tag CI success
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          check_runs_api="https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${TAG_COMMIT_SHA}/check-runs?per_page=100"
          max_attempts=40
          sleep_seconds=15

          for attempt in $(seq 1 "${max_attempts}"); do
            checks_payload="$(curl -fsSL \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "${check_runs_api}")"

            discipline_status="$(
              jq -r '
                .check_runs
                | map(select(.name == "Release Tag Discipline"))
                | sort_by(.started_at // .completed_at // .created_at)
                | reverse
                | (.[0].status // "")
              ' <<<"${checks_payload}"
            )"
            discipline_conclusion="$(
              jq -r '
                .check_runs
                | map(select(.name == "Release Tag Discipline"))
                | sort_by(.started_at // .completed_at // .created_at)
                | reverse
                | (.[0].conclusion // "")
              ' <<<"${checks_payload}"
            )"
            discipline_url="$(
              jq -r '
                .check_runs
                | map(select(.name == "Release Tag Discipline"))
                | sort_by(.started_at // .completed_at // .created_at)
                | reverse
                | (.[0].details_url // "")
              ' <<<"${checks_payload}"
            )"

            if [ "${discipline_status}" = "completed" ] && [ "${discipline_conclusion}" = "success" ]; then
              echo "release-tag discipline passed: ${discipline_url}"
              break
            fi

            if [ "${discipline_status}" = "completed" ] && [ -n "${discipline_conclusion}" ] && [ "${discipline_conclusion}" != "success" ]; then
              echo "release-tag discipline check failed (${discipline_conclusion}): ${discipline_url}" >&2
              exit 1
            fi

            if [ "${attempt}" -eq "${max_attempts}" ]; then
              echo "timed out waiting for successful release-tag discipline check-run for commit ${TAG_COMMIT_SHA}" >&2
              exit 1
            fi

            echo "attempt ${attempt}/${max_attempts}: waiting for release-tag discipline check-run success..."
            sleep "${sleep_seconds}"
          done

      - name: Validate changelog + release notes completeness
        run: bash tools/check-release-tag-discipline.sh --tag "${RELEASE_TAG}"

      - name: Validate annotated signed release tag
        run: |
          git cat-file -e "${RELEASE_TAG}^{tag}"
          TAG_OBJECT_SHA="$(git rev-parse "${RELEASE_TAG}^{tag}")"
          git cat-file -p "${RELEASE_TAG}^{tag}" > "arco-${RELEASE_TAG}.tag-object.txt"

          if ! rg -q '^-----BEGIN (PGP|SSH) SIGNATURE-----$' "arco-${RELEASE_TAG}.tag-object.txt"; then
            echo "release tag must include a PGP or SSH signature block: ${RELEASE_TAG}" >&2
            exit 1
          fi

          if ! git -c gpg.format=ssh -c gpg.ssh.allowedSignersFile=".github/release-signers.allowed" \
            verify-tag "${RELEASE_TAG}" > "arco-${RELEASE_TAG}.tag-verify.txt" 2>&1; then
            echo "release tag signature verification failed against .github/release-signers.allowed for ${RELEASE_TAG}" >&2
            cat "arco-${RELEASE_TAG}.tag-verify.txt" >&2
            exit 1
          fi

      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          toolchain: 1.85

      - name: Install cargo-sbom
        uses: taiki-e/install-action@288875dd3d64326724fa6d9593062d9f8ba0b131 # v2
        with:
          tool: cargo-sbom@0.10.0

      - name: Generate SBOM (SPDX JSON)
        run: cargo sbom --output-format spdx_json_2_3 > "${SBOM_SPDX_FILE}"

      - name: Generate SBOM (CycloneDX JSON)
        run: cargo sbom --output-format cyclone_dx_json_1_6 > "${SBOM_CYCLONEDX_FILE}"

      - name: Generate SBOM checksum manifest
        run: |
          sha256sum "${SBOM_SPDX_FILE}" "${SBOM_CYCLONEDX_FILE}" > "${SBOM_SHA256_FILE}"

      - name: Upload release SBOM artifact pack (retained)
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: release-sbom-${{ env.RELEASE_TAG }}
          retention-days: ${{ env.SBOM_RETENTION_DAYS }}
          if-no-files-found: error
          path: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}
            arco-${{ env.RELEASE_TAG }}.tag-object.txt
            arco-${{ env.RELEASE_TAG }}.tag-verify.txt

      - name: Publish build provenance attestation for SBOM artifacts
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-path: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}

      - name: Attach SBOM files to GitHub release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ${{ env.SBOM_SPDX_FILE }}
            ${{ env.SBOM_CYCLONEDX_FILE }}
            ${{ env.SBOM_SHA256_FILE }}

      - name: Build immutable release evidence pack
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          PACK_DIR="$(bash tools/collect_release_evidence.sh --tag "${RELEASE_TAG}" --output-root ".gate1-collector")"
          echo "PACK_DIR=${PACK_DIR}" >> "${GITHUB_ENV}"

      - name: Archive release evidence pack
        run: |
          tar -C "$(dirname "${PACK_DIR}")" -czf "${EVIDENCE_ARCHIVE}" "$(basename "${PACK_DIR}")"

      - name: Upload release evidence pack artifact (retained)
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: release-evidence-${{ env.RELEASE_TAG }}
          retention-days: ${{ env.SBOM_RETENTION_DAYS }}
          if-no-files-found: error
          path: ${{ env.EVIDENCE_ARCHIVE }}
